name: Build and Push (Frontend + Backend) to GHCR
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: backend
            context: ./orgjet-backend
            image: orgjet-backend
            # no build args for backend
          - name: frontend
            context: ./orgjet-frontend
            image: orgjet-frontend
            # build arg: bake API base for local k8s port-forward
            build_args: |
              VITE_API_BASE=http://localhost:3000
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: lc
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:latest
          build-args: |
            VITE_API_BASE=http://localhost:3000